### ISSUE TITLE
Improve install options

### ISSUE THREAD

**Issue by johntdyer** [mjmccans/airthings-mqtt-ha#4]
IT would be great if this was available as a system add-on or as a HAC's plugin.  Just a thought especially for folks running on HASSOS

**Comment by mjmccans** [comment]
This is a good suggestion and I may look into it because I have recently moved my Home Assistant installation from a VM running Debian to an Odroid-N2+ running HassOS. However, the Odroid does not have built in bluetooth and I do not have a compatible adapter so I am still running my script on a Raspberry Pi and feeding the data to my Home Assistant installation via MQTT. If I do get my hands on a bluetooth adapter for the Odroid I will look into moving the script over and update this Issue.

**Comment by mjmccans** [comment]
In case you would find it helpful, I have now packaged the script as an add-on and it can be found in my [hassio-addon-airthings](https://github.com/mjmccans/hassio-addon-airthings) repository. It is working well for me but please test it out if it would be helpful for you and let me know if it works or if you have any issues getting it working.

**Comment by mjmccans** [comment]
Closing this issue given that an add-on is now available, but please let me know if it is not working for you.
